### ISSUE TITLE
IoT SiteWise Grafana Plugin Giving "Metric request error"

### ISSUE THREAD

**Issue by nenadilic84** [grafana/iot-sitewise-datasource#81]
When adding multiple panels that use the IoT SiteWise Grafana Plugin as a data source, a query error appears after a dashboard refresh.

After manually going to the Query inspector and hiting Query->Referesh the panel info is displyed, but other panales in the same dashboard will then have the same issue "Metric request error".

Grafana Version: 7.4.0
AWS IoT SiteWise Datasource Version: 1.0.0

**Comment by bymattoa** [comment]
Adding image from ticket

![image](https://user-images.githubusercontent.com/19557121/107983464-a8959280-6f7a-11eb-9a9d-4fc3076b4352.png)

**Comment by bymattoa** [comment]
Are there any additional error details when hovering over the notification, or looking at the query inspector?

**Comment by nenadilic84** [comment]
yes, I get the 500 as a response of the query

**Comment by nenadilic84** [comment]
Logs for reference:

```
t=2021-02-15T19:26:43+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_a
ddr=54.239.6.186 time_ms=148 size=34 referer="https://xxx.xxx.com.tr/d/axVVVBPMk/xxx?orgId=1"
t=2021-02-15T19:26:43+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unavailable desc = tra
nsport is closing" remote_addr=54.239.6.186
t=2021-02-15T19:26:43+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_a
ddr=54.239.6.186 time_ms=148 size=34 referer="https://xxx.xxx.com.tr/d/axVVVBPMk/xxx?orgId=1"
t=2021-02-15T19:26:43+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unavailable desc = tra
nsport is closing" remote_addr=54.239.6.186
t=2021-02-15T19:26:43+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_a
ddr=54.239.6.186 time_ms=148 size=34 referer="https://xxx.xxx.com.tr/d/axVVVBPMk/xxx?orgId=1"
t=2021-02-15T19:26:43+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unavailable desc = tra
nsport is closing" remote_addr=54.239.6.186
t=2021-02-15T19:26:43+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_a
ddr=54.239.6.186 time_ms=148 size=34 referer="https://xxx.xxx.com.tr/d/axVVVBPMk/xxx?orgId=1"
t=2021-02-15T19:26:43+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unavailable desc = tra
nsport is closing" remote_addr=54.239.6.186
t=2021-02-15T19:26:43+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_a
ddr=54.239.6.186 time_ms=153 size=34 referer="https://xxx.xxx.com.tr/d/axVVVBPMk/xxx?orgId=1"
t=2021-02-15T19:26:43+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unavailable desc = con
nection error: desc = \"transport: error while dialing: dial unix /tmp/plugin037062202: connect: connection refused\"" remote_addr=54.239.6.186
t=2021-02-15T19:26:43+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_a
ddr=54.239.6.186 time_ms=1 size=34 referer="https://xxx.xxx.com.tr/d/axVVVBPMk/xxx?orgId=1"
t=2021-02-15T19:26:43+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unavailable desc = con
nection error: desc = \"transport: error while dialing: dial unix /tmp/plugin037062202: connect: connection refused\"" remote_addr=54.239.6.186
t=2021-02-15T19:26:43+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_a
ddr=54.239.6.186 time_ms=2 size=34 referer="https://xxx.xxx.com.tr/d/axVVVBPMk/xxx?orgId=1"
t=2021-02-15T19:26:43+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unavailable desc = con
nection error: desc = \"transport: error while dialing: dial unix /tmp/plugin037062202: connect: connection refused\"" remote_addr=54.239.6.186
t=2021-02-15T19:26:43+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_a
ddr=54.239.6.186 time_ms=1 size=34 referer="https://xxx.xxx.com.tr/d/axVVVBPMk/xxx?orgId=1"
t=2021-02-15T19:26:43+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unavailable desc = con
nection error: desc = \"transport: error while dialing: dial unix /tmp/plugin037062202: connect: connection refused\"" remote_addr=54.239.6.186
t=2021-02-15T19:26:43+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_a
ddr=54.239.6.186 time_ms=0 size=34 referer="https://xxx.xxx.com.tr/d/axVVVBPMk/xxx?orgId=1"
t=2021-02-15T19:26:43+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unavailable desc = con
nection error: desc = \"transport: error while dialing: dial unix /tmp/plugin037062202: connect: connection refused\"" remote_addr=54.239.6.186
t=2021-02-15T19:26:43+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_a
ddr=54.239.6.186 time_ms=1 size=34 referer="https://xxx.xxx.com.tr/d/axVVVBPMk/xxx?orgId=1"
t=2021-02-15T19:26:43+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unavailable desc = con
nection error: desc = \"transport: error while dialing: dial unix /tmp/plugin037062202: connect: connection refused\"" remote_addr=54.239.6.186
t=2021-02-15T19:26:43+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_a
ddr=54.239.6.186 time_ms=2 size=34 referer="https://xxx.xxx.com.tr/d/axVVVBPMk/xxx?orgId=1"
t=2021-02-15T19:26:43+0000 lvl=info msg=Profiler logger=plugins.backend pluginId=grafana-iot-sitewise-datasource enabled=false
t=2021-02-15T19:26:58+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.192.11.152 
time_ms=0 size=29 referer=
t=2021-02-15T19:27:00+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=10.192.10.30 t
ime_ms=0 size=29 referer=
t=2021-02-15T19:27:11+0000 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="rpc error: code = Unavailable desc = tra
nsport is closing" remote_addr=54.239.6.186
t=2021-02-15T19:27:11+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_a
ddr=54.239.6.186 time_ms=150 size=34 referer="https://xxx.xxx.com.tr/d/axVVVBPMk/xxx?orgId=1
"
t=2021-02-15T19:27:11+0000 lvl=info msg=Profiler logger=plugins.backend pluginId=grafana-iot-sitewise-datasource enabled=false
```

**Comment by bymattoa** [comment]
Looks like we are not correctly handling the empty response for `GetAssetPropertyValue` in the framer:

https://github.com/grafana/iot-sitewise-datasource/blob/main/pkg/framer/property_value.go#L30

Will send a fix out

**Comment by nenadilic84** [comment]
Just to add that this is occurring in the case where a single panel does not have a valid measurement, others may report `Metric request error` even though there was no error upon a request

**Comment by ryantxu** [comment]
Fixed by #82, but still needs to be released.

@nenadilic84 are you able to use a dev build to verify?  To get the latest dev build see:
https://github.com/grafana/iot-sitewise-datasource#development-builds

**Comment by emrahacikalin** [comment]
Hi,

This issue still exists, @ryantxu could you please re-open it?

Grafana Version: 7.5.7 (91de51771c)
AWS IoT SiteWise Datasource Version: 1.2.3


t=2021-05-30T18:57:39+0000 lvl=eror msg="Request Completed" logger=context userId=XXX orgId=XXX uname=XXX method=POST path=/api/ds/query status=500 remote_addr=XXX.XXX.XXX.XXX time_ms=48 size=34 referer="https://XXX/d/XXX/XXX$
t=2021-05-30T18:57:40+0000 lvl=info msg=Profiler logger=plugins.backend pluginId=grafana-iot-sitewise-datasource enabled=false


![image](https://user-images.githubusercontent.com/52149102/120116825-a86c7c00-c192-11eb-91c0-d04e75396ef8.png)
![image](https://user-images.githubusercontent.com/52149102/120117075-21b89e80-c194-11eb-8c41-4139b98092ec.png)
![image](https://user-images.githubusercontent.com/52149102/120116972-92ab8680-c193-11eb-90a4-49f772e1278d.png)
